# Generated by Django 2.2.24 on 2024-10-29 13:46

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20241029_1624'),
    ]

    operations = [
    ]
