# Generated by Django 2.2.24 on 2024-10-29 14:20

from django.db import migrations
import phonenumbers

def replace_phonenumbers(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all():
        flat.owner_pure_phone = None
        flat.save()

def update_phonenumbers(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all():
        normal_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if not phonenumbers.is_possible_number(normal_number):
            normal_number = None

        flat.owner_pure_phone = normal_number

        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20241029_1716'),
    ]

    operations = [
        migrations.RunPython(update_phonenumbers, replace_phonenumbers)
    ]
