# Generated by Django 2.2.24 on 2024-10-29 16:50

from django.db import migrations

def add_owners(apps, schema_editor):
    flats = apps.get_model('property','Flat')
    owner = apps.get_model('property','Owner')

    for flat in flats.objects.all():
        owner.objects.get_or_create(name=flat.owner, defaults = {
            'owners_phonenumber': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_owner'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]
