# Generated by Django 2.2.24 on 2024-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20241029_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owned_apartments',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
