# Generated by Django 2.2.24 on 2024-10-31 13:41

from django.db import migrations

def add_owners(apps, schema_editor):
    flats = apps.get_model('property','Flat')
    owners = apps.get_model('property','Owner')

    for owner in owners.objects.all():
        name = owner.name
        phone_number = owner.owners_phonenumber
        owner_flats = flats.objects.filter(owner=name, owners_phonenumber=phone_number)
        owner.owned_apartments.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20241031_1641'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]
