# Generated by Django 2.2.24 on 2024-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20241107_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_apartments',
            new_name='apartments',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
