# Generated by Django 2.2.24 on 2024-11-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20241107_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_name',
            new_name='user',
        ),
    ]
