# Generated by Django 2.2.24 on 2024-11-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20241107_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='decription',
            new_name='description',
        ),
    ]
